import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type TeamStatus = 'Under Review' | 'Pitching' | 'Shortlisted' | 'Eliminated';

export interface TeamMember {
    name: string;
    foodCheckedIn: boolean;
}

export interface Team {
    id: string;
    position: number;
    teamName: string;
    projectName: string;
    category: string;
    status: TeamStatus;
    score: number;
    leads: string[];
    members: TeamMember[];
    foodCheckedIn: boolean;
    roomNumber?: string;
    timeSlot?: string;
    presentationUrl?: string;
    certificateUrl?: string;
}

interface LeaderboardState {
    teams: Team[];
    updateTeamStatus: (id: string, status: TeamStatus) => void;
    getTeamById: (id: string) => Team | undefined;
    getTeamByName: (name: string) => Team | undefined;
    toggleTeamFood: (id: string) => void;
    toggleMemberFood: (teamId: string, memberName: string) => void;
}

const mockTeams: Team[] = [
    {
        id: 'uo8d036u',
        position: 1,
        teamName: 'Axasians',
        projectName: 'Axasians',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Akhilesh Badrinath'],
        members: [
            { name: 'Akhilesh Badrinath', foodCheckedIn: false },
            { name: 'Ananya Chakraborty', foodCheckedIn: false },
            { name: 'Adhya Viju', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-5',
    },
    {
        id: 'u8t47j0l',
        position: 2,
        teamName: 'Grey-MatterX',
        projectName: 'Grey-MatterX',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Ajay Mudliyar'],
        members: [
            { name: 'Ajay Mudliyar', foodCheckedIn: false },
            { name: 'Tanishq Mudaliyar', foodCheckedIn: false },
            { name: 'Vignesh Valluvan', foodCheckedIn: false },
            { name: 'Vasanth Nadar', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'u02s8gb2',
        position: 3,
        teamName: 'Mad Mavericks',
        projectName: 'Mad Mavericks',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['ANISH MANJREKAR'],
        members: [
            { name: 'ANISH MANJREKAR', foodCheckedIn: false },
            { name: 'Shlok Dhawan', foodCheckedIn: false },
            { name: 'Bhushan Parab', foodCheckedIn: false },
            { name: 'Likhit Rane', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'u41zf63k',
        position: 4,
        teamName: 'Good Fellas',
        projectName: 'Good Fellas',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Sudharsan Nadar'],
        members: [
            { name: 'Sudharsan Nadar', foodCheckedIn: false },
            { name: 'Ilavarasu Thevar', foodCheckedIn: false },
            { name: 'Tanish Srinivasan', foodCheckedIn: false },
            { name: 'Steve Jason', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'u771czi9',
        position: 5,
        teamName: 'Vishal.CJ',
        projectName: 'Vishal.CJ',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Vishal CJ'],
        members: [
            { name: 'Vishal CJ', foodCheckedIn: false },
            { name: 'Sabarish GK', foodCheckedIn: false },
            { name: 'Ruban', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'u072wqg8',
        position: 6,
        teamName: 'Redstone Crafters',
        projectName: 'Redstone Crafters',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Naresh T'],
        members: [
            { name: 'Naresh T', foodCheckedIn: false },
            { name: 'Vrushabh Shirke', foodCheckedIn: false },
            { name: 'Tirthesh Tandel', foodCheckedIn: false },
            { name: 'SriPranav Rajaram', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-6',
    },
    {
        id: 'u51l5e6u',
        position: 7,
        teamName: 'CRUX',
        projectName: 'CRUX',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Tarun Rajeev Rajauria'],
        members: [
            { name: 'Tarun Rajeev Rajauria', foodCheckedIn: false },
            { name: 'Abhijeet Shriniwas Sapar', foodCheckedIn: false },
            { name: 'Kalash Paras Bheda', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-7',
    },
    {
        id: 'ul93qd88',
        position: 8,
        teamName: 'EdgeVision',
        projectName: 'EdgeVision',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Nitya Nadar'],
        members: [
            { name: 'Nitya Nadar', foodCheckedIn: false },
            { name: 'Priyanka Vijaya Sundaram Gounder', foodCheckedIn: false },
            { name: 'Imaad Fodkar', foodCheckedIn: false },
            { name: 'Karthika Thevar', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-5',
    },
    {
        id: 'uqv3n929',
        position: 9,
        teamName: 'SaccharoTech',
        projectName: 'SaccharoTech',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Niha Solkar'],
        members: [
            { name: 'Niha Solkar', foodCheckedIn: false },
            { name: 'Shloka Suvarna', foodCheckedIn: false },
            { name: 'Anshul Choudhari', foodCheckedIn: false },
            { name: 'Shreeya Bhalerao', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'uh9799gs',
        position: 10,
        teamName: 'AlgoX',
        projectName: 'AlgoX',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Vaishnavi Thorat'],
        members: [
            { name: 'Vaishnavi Thorat', foodCheckedIn: false },
            { name: 'Pavitra Warrier', foodCheckedIn: false },
            { name: 'Namish Sharma', foodCheckedIn: false },
            { name: 'Taazeen Ansari', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-6',
    },
    {
        id: 'u74sk1l1',
        position: 11,
        teamName: 'REDOXX',
        projectName: 'REDOXX',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Ankur Kumar Singh'],
        members: [
            { name: 'Ankur Kumar Singh', foodCheckedIn: false },
            { name: 'Anjali Nitin Samant', foodCheckedIn: false },
            { name: 'Yashraj Arvind Tripathi', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'ut5376pb',
        position: 12,
        teamName: 'TrioCoders',
        projectName: 'TrioCoders',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Ishita Poonja'],
        members: [
            { name: 'Ishita Poonja', foodCheckedIn: false },
            { name: 'Pooja Sriram', foodCheckedIn: false },
            { name: 'Falguni Patil', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'u22j9n6r',
        position: 13,
        teamName: 'Team 404',
        projectName: 'Team 404',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Pavitra Boga'],
        members: [
            { name: 'Pavitra Boga', foodCheckedIn: false },
            { name: 'Akshata Chettiar', foodCheckedIn: false },
            { name: 'Kaveesh Kadirvel', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'u8vgc540',
        position: 14,
        teamName: 'Dev Ally',
        projectName: 'Dev Ally',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Yash Nimse'],
        members: [
            { name: 'Yash Nimse', foodCheckedIn: false },
            { name: 'Aryan Shinde', foodCheckedIn: false },
            { name: 'Ayush Jagtap', foodCheckedIn: false },
            { name: 'Nirmal Darekar', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'ui3ao589',
        position: 15,
        teamName: 'TechPulse',
        projectName: 'TechPulse',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Sejal Vartak'],
        members: [
            { name: 'Sejal Vartak', foodCheckedIn: false },
            { name: 'Ibrahim Abdul Ahad Khan', foodCheckedIn: false },
            { name: 'Janhvi Dhale', foodCheckedIn: false },
            { name: 'Gandhar Bagde', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'u0cz60a8',
        position: 16,
        teamName: 'Memory miners',
        projectName: 'Memory miners',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Sanjana Yadav'],
        members: [
            { name: 'Sanjana Yadav', foodCheckedIn: false },
            { name: 'Vinita Narayanan', foodCheckedIn: false },
            { name: 'Shashank Kutty', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'uf24bd33',
        position: 17,
        teamName: 'Power Rangers',
        projectName: 'Power Rangers',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Aarthi Chettiar'],
        members: [
            { name: 'Aarthi Chettiar', foodCheckedIn: false },
            { name: 'Hari Shanker Iyer', foodCheckedIn: false },
            { name: 'Krishni Subenthiran', foodCheckedIn: false },
            { name: 'Anoushka Rajesh', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'u4y77bq2',
        position: 18,
        teamName: 'Synergy Squad',
        projectName: 'Synergy Squad',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Gopikha G U'],
        members: [
            { name: 'Gopikha G U', foodCheckedIn: false },
            { name: 'Maharajan Konar', foodCheckedIn: false },
            { name: 'Sourish Kanna', foodCheckedIn: false },
            { name: 'Nandini Shende', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'uc1p17v9',
        position: 19,
        teamName: 'Synapse',
        projectName: 'Synapse',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Aditya Waradkar'],
        members: [
            { name: 'Aditya Waradkar', foodCheckedIn: false },
            { name: 'Aditya Raman', foodCheckedIn: false },
            { name: 'Manav Sadh', foodCheckedIn: false },
            { name: 'Pavithra Lokesh', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-7',
    },
    {
        id: 'uf8v575u',
        position: 20,
        teamName: 'PDS26',
        projectName: 'PDS26',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Kesavan Kumar Mudaliyar'],
        members: [
            { name: 'Kesavan Kumar Mudaliyar', foodCheckedIn: false },
            { name: 'K Nisharani Kamesh Babu', foodCheckedIn: false },
            { name: 'Mahalakshmi Gounder', foodCheckedIn: false },
            { name: 'nishok ganapathy', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'u73f73mh',
        position: 21,
        teamName: 'Team Transformers',
        projectName: 'Team Transformers',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Talha Patrawala'],
        members: [
            { name: 'Talha Patrawala', foodCheckedIn: false },
            { name: 'Shreyansh Chauhan', foodCheckedIn: false },
            { name: 'Shubham Dombale', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-5',
    },
    {
        id: 'uj96h53v',
        position: 22,
        teamName: 'SolarX',
        projectName: 'SolarX',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Aryaan Pradeep Gala'],
        members: [
            { name: 'Aryaan Pradeep Gala', foodCheckedIn: false },
            { name: 'Jash Keyur Barbhaya', foodCheckedIn: false },
            { name: 'Rajat Chandarana', foodCheckedIn: false },
            { name: 'Gurdev Singh Dhanjal', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'um0l999g',
        position: 23,
        teamName: 'Aero Nova',
        projectName: 'Aero Nova',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Abeerah Khan'],
        members: [
            { name: 'Abeerah Khan', foodCheckedIn: false },
            { name: 'Nidhi Beloshe', foodCheckedIn: false },
            { name: 'Himanshu Dwivedi', foodCheckedIn: false },
            { name: 'Adwita Padhye', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-6',
    },
    {
        id: 'uek9u046',
        position: 24,
        teamName: 'Algorithmic Alchemists',
        projectName: 'Algorithmic Alchemists',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Harsh Sandip Ambre'],
        members: [
            { name: 'Harsh Sandip Ambre', foodCheckedIn: false },
            { name: 'Vishavas Dattatray Ichake', foodCheckedIn: false },
            { name: 'Sujal Kishor Patil', foodCheckedIn: false },
            { name: 'Dhruv Raval', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'ux766jm9',
        position: 25,
        teamName: 'BangerBrains',
        projectName: 'BangerBrains',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Shevante Prajwal Dilip'],
        members: [
            { name: 'Shevante Prajwal Dilip', foodCheckedIn: false },
            { name: 'Jatin Jagannath Shetty', foodCheckedIn: false },
            { name: 'Shivam Mane', foodCheckedIn: false },
            { name: 'Monish Sasikumar', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'upo43j15',
        position: 26,
        teamName: 'Cicada Cipher',
        projectName: 'Cicada Cipher',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Aashika Nadar'],
        members: [
            { name: 'Aashika Nadar', foodCheckedIn: false },
            { name: 'Srushti Dhake', foodCheckedIn: false },
            { name: 'Chandhru Nadar', foodCheckedIn: false },
            { name: 'Mugesh Nadar', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'u7785sym',
        position: 27,
        teamName: 'ZephyrBots',
        projectName: 'ZephyrBots',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Ishita Singh'],
        members: [
            { name: 'Ishita Singh', foodCheckedIn: false },
            { name: 'Pritesh Shetty', foodCheckedIn: false },
            { name: 'Rehan Shaikh', foodCheckedIn: false },
            { name: 'Amey Shigam', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'un531f5k',
        position: 28,
        teamName: 'Wealth Wizards',
        projectName: 'Wealth Wizards',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Krishant Arivalagan'],
        members: [
            { name: 'Krishant Arivalagan', foodCheckedIn: false },
            { name: 'Anurag Mohit', foodCheckedIn: false },
            { name: 'Omkar Choughule', foodCheckedIn: false },
            { name: 'Arjunan Swamynathan', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'u2h9c9d7',
        position: 29,
        teamName: 'QuadraCore',
        projectName: 'QuadraCore',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Arya Muthukrishnan'],
        members: [
            { name: 'Arya Muthukrishnan', foodCheckedIn: false },
            { name: 'Dhrithi Moolya', foodCheckedIn: false },
            { name: 'Nanmathi Balachandran', foodCheckedIn: false },
            { name: 'Manikaraj Anburaj', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'u3j92g7l',
        position: 30,
        teamName: 'Nullpointer',
        projectName: 'Nullpointer',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Jay Nehhal Cheda'],
        members: [
            { name: 'Jay Nehhal Cheda', foodCheckedIn: false },
            { name: 'Saiprasad Jamdar', foodCheckedIn: false },
            { name: 'Tanish Shah', foodCheckedIn: false },
            { name: 'Krishita Ravat', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'u7dv99t5',
        position: 31,
        teamName: 'Code Wreckers',
        projectName: 'Code Wreckers',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Dwithi Poojary'],
        members: [
            { name: 'Dwithi Poojary', foodCheckedIn: false },
            { name: 'Atharva Ketkar', foodCheckedIn: false },
            { name: 'Atharva Khandagale', foodCheckedIn: false },
            { name: 'Sri Muthu Lakshmanan RK', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'u7uzp185',
        position: 32,
        teamName: 'TerraGuardians',
        projectName: 'TerraGuardians',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Nimish ROGE'],
        members: [
            { name: 'Nimish ROGE', foodCheckedIn: false },
            { name: 'Hariom Mohare', foodCheckedIn: false },
            { name: 'Maadeshselvan', foodCheckedIn: false },
            { name: 'Manas Suryavanshi', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-7',
    },
    {
        id: 'um39il66',
        position: 33,
        teamName: 'Synergy',
        projectName: 'Synergy',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Soham Somavanshi'],
        members: [
            { name: 'Soham Somavanshi', foodCheckedIn: false },
            { name: 'Vishnu Vardhan Subramanyam', foodCheckedIn: false },
            { name: 'Vinay Sawant', foodCheckedIn: false },
            { name: 'Saran Rajasekhar', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'ua1qz476',
        position: 34,
        teamName: 'Om Sai Mitra Mandal',
        projectName: 'Om Sai Mitra Mandal',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Suthakar Anburaj'],
        members: [
            { name: 'Suthakar Anburaj', foodCheckedIn: false },
            { name: 'Gokul Srinivasan', foodCheckedIn: false },
            { name: 'Omkar Chavan', foodCheckedIn: false },
            { name: 'Tanmay Dhole', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'u503njo4',
        position: 35,
        teamName: 'Technoblade',
        projectName: 'Technoblade',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Tushar Singh'],
        members: [
            { name: 'Tushar Singh', foodCheckedIn: false },
            { name: 'Shubham Singh', foodCheckedIn: false },
            { name: 'Niharika Singh', foodCheckedIn: false },
            { name: 'Bhoomi Sharma', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'ut751hg7',
        position: 36,
        teamName: 'Geosense',
        projectName: 'Geosense',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['IRIS MARSHAL SOJ'],
        members: [
            { name: 'IRIS MARSHAL SOJ', foodCheckedIn: false },
            { name: 'Piyush Deshmukh', foodCheckedIn: false },
            { name: 'Harsshita Vontivillu', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'u19a3y3c',
        position: 37,
        teamName: 'Medifly',
        projectName: 'Medifly',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Aditya Koparkar'],
        members: [
            { name: 'Aditya Koparkar', foodCheckedIn: false },
            { name: 'Samiksha Dhole', foodCheckedIn: false },
            { name: 'Sarang Patil', foodCheckedIn: false },
            { name: 'Inesh Banerjee', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-5',
    },
    {
        id: 'u7z87hu8',
        position: 38,
        teamName: 'Abhiram',
        projectName: 'Abhiram',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Abhiram Nair'],
        members: [
            { name: 'Abhiram Nair', foodCheckedIn: false },
            { name: 'Vedant', foodCheckedIn: false },
            { name: 'Aaditya', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'u1qra195',
        position: 39,
        teamName: 'The visionaries',
        projectName: 'The visionaries',
        category: 'HARDWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Rahul Nadar'],
        members: [
            { name: 'Rahul Nadar', foodCheckedIn: false },
            { name: 'Monika Choudhary', foodCheckedIn: false },
            { name: 'Ayaan Mulla', foodCheckedIn: false },
            { name: 'Kunal Samanta', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'LAB-6',
    },
    {
        id: 'u07i3oz8',
        position: 40,
        teamName: 'Team WildSight',
        projectName: 'Team WildSight',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Shruti Subramanian'],
        members: [
            { name: 'Shruti Subramanian', foodCheckedIn: false },
            { name: 'aarya varsolkar', foodCheckedIn: false },
            { name: 'Mitesh Naik', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'u78z19vi',
        position: 41,
        teamName: 'Code Catalysts',
        projectName: 'Code Catalysts',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Purva Dutta'],
        members: [
            { name: 'Purva Dutta', foodCheckedIn: false },
            { name: 'Samruddhi Bhalekar', foodCheckedIn: false },
            { name: 'Anurag Thakur', foodCheckedIn: false },
            { name: 'Harsh Mhatre', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'ul6ur399',
        position: 42,
        teamName: 'Pseudo Bots',
        projectName: 'Pseudo Bots',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Amit Sunil Ramtri'],
        members: [
            { name: 'Amit Sunil Ramtri', foodCheckedIn: false },
            { name: 'Harsh Dinesh Maghnani', foodCheckedIn: false },
            { name: 'Deepesh Uttamchand Navani', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
    {
        id: 'u2d4l03q',
        position: 43,
        teamName: 'MoneyMappers',
        projectName: 'MoneyMappers',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Om Tawde'],
        members: [
            { name: 'Om Tawde', foodCheckedIn: false },
            { name: 'Parth Varekar', foodCheckedIn: false },
            { name: 'Sumit Singh', foodCheckedIn: false },
            { name: 'Tanay Shinde', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'IEM',
    },
    {
        id: 'uv5137tj',
        position: 44,
        teamName: 'CodeByte',
        projectName: 'CodeByte',
        category: 'SOFTWARE',
        status: 'Under Review' as TeamStatus,
        score: 0,
        leads: ['Indrayani Patil'],
        members: [
            { name: 'Indrayani Patil', foodCheckedIn: false },
            { name: 'Nishalini Kanthakumar', foodCheckedIn: false },
            { name: 'Khushi Patil', foodCheckedIn: false },
        ],
        foodCheckedIn: false,
        roomNumber: 'GST AUDI',
    },
];

export const useLeaderboardStore = create<LeaderboardState>()(
    persist(
        (set, get) => ({
            teams: mockTeams,
            updateTeamStatus: (id, status) =>
                set((state) => ({
                    teams: state.teams.map((t) => (t.id === id ? { ...t, status } : t)),
                })),
            getTeamById: (id) => get().teams.find((t) => t.id === id),
            getTeamByName: (name) => {
                const lower = name.toLowerCase().trim();
                return get().teams.find((t) => t.teamName.toLowerCase() === lower);
            },
            toggleTeamFood: (id) =>
                set((state) => ({
                    teams: state.teams.map((t) =>
                        t.id === id
                            ? {
                                ...t,
                                foodCheckedIn: !t.foodCheckedIn,
                                members: t.members.map((m) => ({
                                    ...m,
                                    foodCheckedIn: !t.foodCheckedIn,
                                })),
                            }
                            : t
                    ),
                })),
            toggleMemberFood: (teamId, memberName) =>
                set((state) => ({
                    teams: state.teams.map((t) => {
                        if (t.id !== teamId) return t;
                        const updatedMembers = t.members.map((m) =>
                            m.name === memberName
                                ? { ...m, foodCheckedIn: !m.foodCheckedIn }
                                : m
                        );
                        const allCheckedIn = updatedMembers.every((m) => m.foodCheckedIn);
                        return { ...t, members: updatedMembers, foodCheckedIn: allCheckedIn };
                    }),
                })),
        }),
        {
            name: 'innovations-leaderboard',
        }
    )
);
